#!/bin/bash
#SBATCH --job-name=synthetic_array
#SBATCH --partition=cpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --array=0-55%4
#SBATCH --time=02:00:00    
#SBATCH --mem=15G       
#SBATCH --output=/storage/DSH/projects/neuroart/uncertainty_ml/.sbatch_logs/%x_%A_%a_stdOut.txt
#SBATCH --error=/storage/DSH/projects/neuroart/uncertainty_ml/.sbatch_logs/%x_%A_%a_stdErr.txt

# --- Container Configuration ---
#SBATCH --container-image="/storage/DSH/projects/neuroart/uncertainty_ml/.container_files/ml_environment.sqsh"
#SBATCH --container-mounts="/storage/DSH/projects/neuroart/"

# ─────────────────────────────────────────────────────────────────
# STEP 0 — Prerequisites (run these ONCE before submitting the array)
#
# 1. Generate synthetic data:
#    python3 synthetic_generator.py
#    (outputs synthetic_data/ with manifest.csv)
#
# 2. Generate configs and commands file:
#    python3 generate_synthetic_configs.py \
#        --manifest  ../data/synthetic_data/manifest.csv \
#        --template  config_synthetic_template.ini \
#        --code_path /storage/DSH/projects/neuroart/uncertainty_ml/code_classification \
#        --script    main_calibrate.py \
#        --output    ../data/synthetic_data/synthetic_commands.txt
#
# 3. Check the printed array size and update --array above accordingly.
#    Default grid: 7 × 4 × 2 = 56 conditions → --array=0-55
# ─────────────────────────────────────────────────────────────────

# Path to the commands file generated by generate_synthetic_configs.py
COMMANDS_FILE="/storage/DSH/projects/neuroart/uncertainty_ml/data/synthetic_data/synthetic_commands.txt"

# Navigate to the working directory
cd /storage/DSH/projects/neuroart/uncertainty_ml/code_classification

# Ensure Python can find the lib folder
export PYTHONPATH="/storage/DSH/projects/neuroart/uncertainty_ml:$PYTHONPATH"

# Extract the command for this array task (0-indexed)
# Each line in COMMANDS_FILE is one python3 main_calibrate.py --config <path> call
CURRENT_COMMAND=$(sed -n "$((SLURM_ARRAY_TASK_ID + 1))p" "$COMMANDS_FILE")

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Array Task ID : $SLURM_ARRAY_TASK_ID"
echo "Command       : $CURRENT_COMMAND"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Execute
eval $CURRENT_COMMAND